#!/usr/bin/env python3
"""
packages_config_to_csproj.py

Converts one or more packages.config files into synthetic .csproj files
with <PackageReference> entries that Semgrep Supply Chain can consume
via `semgrep ci --allow-local-builds`.

Each synthetic .csproj is placed in its own subdirectory (_semgrep_sc/)
next to the packages.config. This avoids the MSB1050 error that occurs
when dotnet restore finds multiple .csproj files in the same folder.

When --validate-restore is passed the script:
  1. Writes all packages.config entries as <PackageReference>
  2. Runs dotnet restore, stripping NU1202-incompatible packages as needed
  3. Parses obj/project.assets.json to identify which packages are truly
     direct (listed in projectFileDependencyGroups) vs transitive
  4. Rewrites the synthetic .csproj with ONLY the true direct packages
  5. Runs dotnet restore a final time so the lockfile reflects the correct
     direct/transitive split that Semgrep Supply Chain will read

Usage:
    # Single file, output to stdout
    python packages_config_to_csproj.py packages.config

    # Single file, write to specific path
    python packages_config_to_csproj.py packages.config -o MyProject/_semgrep_sc/project.csproj

    # Walk an entire repo and convert every packages.config found
    python packages_config_to_csproj.py --scan-dir ./src

    # Full pipeline: strip incompatibles + resolve direct/transitive split
    python packages_config_to_csproj.py --scan-dir ./src --validate-restore

    # Dry run (print what would be created, don't write)
    python packages_config_to_csproj.py --scan-dir ./src --dry-run
"""

import argparse
import json
import re
import subprocess
import sys
import os
import xml.etree.ElementTree as ET
from pathlib import Path


# ---------------------------------------------------------------------------
# Core conversion logic
# ---------------------------------------------------------------------------

def parse_packages_config(path: Path) -> list[dict]:
    """
    Parse a packages.config file and return a list of package dicts:
      [{"id": "Newtonsoft.Json", "version": "13.0.1", "targetFramework": "net48"}, ...]
    """
    try:
        tree = ET.parse(path)
    except ET.ParseError as e:
        raise ValueError(f"XML parse error in {path}: {e}")

    root = tree.getroot()

    if root.tag == "packages":
        package_elements = root.findall("package")
    elif root.tag == "package":
        package_elements = [root]
    else:
        raise ValueError(f"Unexpected root element <{root.tag}> in {path}. Expected <packages>.")

    packages = []
    for pkg in package_elements:
        pkg_id = pkg.get("id", "").strip()
        version = pkg.get("version", "").strip()

        if not pkg_id:
            print(f"  [WARN] Skipping package entry with no 'id' attribute in {path}", file=sys.stderr)
            continue
        if not version:
            print(f"  [WARN] Package '{pkg_id}' has no 'version' attribute - skipping", file=sys.stderr)
            continue

        packages.append({
            "id": pkg_id,
            "version": version,
            "targetFramework": pkg.get("targetFramework", "").strip(),
            "developmentDependency": pkg.get("developmentDependency", "false").lower() == "true",
        })

    return packages


_NET_TFM_ORDER = [
    "net20", "net30", "net35",
    "net40", "net403",
    "net45", "net451", "net452",
    "net46", "net461", "net462",
    "net47", "net471", "net472",
    "net48", "net481",
]


def _tfm_rank(tfm: str) -> int:
    try:
        return _NET_TFM_ORDER.index(tfm.lower())
    except ValueError:
        return len(_NET_TFM_ORDER)


def resolve_target_framework(packages: list[dict], fallback: str = "net48") -> str:
    """Pick the highest TargetFramework across all packages."""
    tfms = list(set(p["targetFramework"] for p in packages if p["targetFramework"]))
    if not tfms:
        return fallback
    highest = max(tfms, key=_tfm_rank)
    if len(tfms) > 1:
        print(
            f"  [INFO] Multiple targetFramework values found: {sorted(tfms)}. "
            f"Using highest '{highest}'.",
            file=sys.stderr,
        )
    return highest


def build_csproj(packages: list[dict], target_framework: str) -> str:
    """Render the synthetic .csproj XML string."""
    lines = [
        '<Project Sdk="Microsoft.NET.Sdk">',
        "",
        "  <!-- AUTO-GENERATED by packages_config_to_csproj.py -->",
        "  <!-- DO NOT EDIT - this file exists solely for Semgrep Supply Chain scanning -->",
        "",
        "  <PropertyGroup>",
        f"    <TargetFramework>{target_framework}</TargetFramework>",
        "    <!-- Allow restore to fall back to older TFM assets (e.g. net35, net40). -->",
        "    <AssetTargetFallback>$(AssetTargetFallback);net45;net40;net35;net20</AssetTargetFallback>",
        "    <!-- Disable build output so this project is never accidentally compiled -->",
        "    <IsPackable>false</IsPackable>",
        "  </PropertyGroup>",
        "",
        "  <ItemGroup>",
    ]

    for pkg in packages:
        comment = ""
        if pkg["developmentDependency"]:
            comment = "  <!-- dev dependency -->"
        lines.append(
            f'    <PackageReference Include="{pkg["id"]}" Version="{pkg["version"]}" />{comment}'
        )

    lines += [
        "  </ItemGroup>",
        "",
        "</Project>",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# project.assets.json parsing - direct vs transitive resolution
# ---------------------------------------------------------------------------

def parse_direct_deps_from_assets(assets_path: Path) -> set[str]:
    """
    Parse obj/project.assets.json and return the set of package IDs that are
    true direct dependencies (i.e. listed in projectFileDependencyGroups).

    projectFileDependencyGroups contains entries like:
        "net48": ["Newtonsoft.Json >= 13.0.1", "Autofac >= 6.5.0"]

    Everything else in the full graph is transitive.

    Returns lowercase package IDs for case-insensitive comparison.
    """
    try:
        with open(assets_path, encoding="utf-8") as f:
            assets = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"  [WARN] Could not parse {assets_path}: {e}", file=sys.stderr)
        return set()

    direct_ids = set()
    dep_groups = assets.get("projectFileDependencyGroups", {})

    for tfm, deps in dep_groups.items():
        for dep in deps:
            # Each entry looks like "PackageName >= 1.2.3" or "PackageName [1.2.3]"
            # We just want the package name — everything before the first space
            pkg_id = dep.split()[0].strip().lower()
            if pkg_id:
                direct_ids.add(pkg_id)

    return direct_ids


def resolve_direct_packages(
    packages: list[dict],
    csproj_path: Path,
) -> tuple[list[dict], list[dict]]:
    """
    After a successful dotnet restore, parse obj/project.assets.json to determine
    which packages from the input list are truly direct vs transitive.

    Returns (direct_packages, transitive_packages).

    If project.assets.json cannot be found or parsed, returns all packages as
    direct (safe fallback - no information lost, just no direct/transitive split).
    """
    assets_path = csproj_path.parent / "obj" / "project.assets.json"

    if not assets_path.exists():
        print(
            f"  [WARN] project.assets.json not found at {assets_path} - "
            f"treating all packages as direct (no direct/transitive split).",
            file=sys.stderr,
        )
        return packages, []

    direct_ids = parse_direct_deps_from_assets(assets_path)

    if not direct_ids:
        print(
            f"  [WARN] No direct deps found in {assets_path} - "
            f"treating all packages as direct.",
            file=sys.stderr,
        )
        return packages, []

    direct = [p for p in packages if p["id"].lower() in direct_ids]
    transitive = [p for p in packages if p["id"].lower() not in direct_ids]

    return direct, transitive


# ---------------------------------------------------------------------------
# Restore validation + incompatible package stripping
# ---------------------------------------------------------------------------

_NU1202_RE = re.compile(
    r"NU1202: Package '?([A-Za-z0-9._\-]+)\s+([\d.]+)'? is not compatible",
    re.IGNORECASE,
)


def _try_restore(csproj_path: Path) -> tuple[bool, list[tuple[str, str]]]:
    """
    Attempt dotnet restore on the synthetic .csproj.
    Returns (success, [(package_id, version), ...]) where the list contains
    any packages that caused NU1202 incompatibility errors.
    """
    result = subprocess.run(
        ["dotnet", "restore", str(csproj_path), "--use-lock-file"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return True, []

    combined = result.stdout + result.stderr
    offenders = []
    for match in _NU1202_RE.finditer(combined):
        offenders.append((match.group(1), match.group(2)))

    return False, offenders


def strip_incompatible_packages(
    packages: list[dict],
    csproj_path: Path,
    target_framework: str,
    max_retries: int = 5,
) -> list[dict]:
    """
    Write the synthetic .csproj, attempt dotnet restore, strip NU1202 offenders,
    and retry up to max_retries times.

    Returns the final list of compatible packages.
    """
    remaining = list(packages)
    skipped = []

    for attempt in range(1, max_retries + 1):
        content = build_csproj(remaining, target_framework)
        csproj_path.parent.mkdir(parents=True, exist_ok=True)
        csproj_path.write_text(content, encoding="utf-8")

        success, offenders = _try_restore(csproj_path)

        if success:
            if skipped:
                print(
                    f"  [INFO] Restore succeeded after stripping {len(skipped)} incompatible "
                    f"package(s): {[p['id'] for p in skipped]}",
                    file=sys.stderr,
                )
            return remaining

        if not offenders:
            print(
                f"  [WARN] Restore failed (attempt {attempt}) for reasons other than NU1202 - "
                f"leaving synthetic .csproj in place.",
                file=sys.stderr,
            )
            return remaining

        offender_ids = {pkg_id.lower() for pkg_id, _ in offenders}
        newly_skipped = [p for p in remaining if p["id"].lower() in offender_ids]
        remaining = [p for p in remaining if p["id"].lower() not in offender_ids]

        for pkg in newly_skipped:
            print(
                f"  [SKIP] {pkg['id']} {pkg['version']} - incompatible with {target_framework} "
                f"(NU1202), excluded from synthetic .csproj",
                file=sys.stderr,
            )
        skipped.extend(newly_skipped)

        if not remaining:
            print(
                f"  [WARN] All packages stripped as incompatible - skipping {csproj_path}",
                file=sys.stderr,
            )
            csproj_path.unlink(missing_ok=True)
            return []

    print(
        f"  [WARN] Still failing after {max_retries} strip attempts - leaving last attempt in place.",
        file=sys.stderr,
    )
    return remaining


# ---------------------------------------------------------------------------
# Convert pipeline
# ---------------------------------------------------------------------------

def convert(
    input_path: Path,
    output_path: Path | None = None,
    dry_run: bool = False,
    validate_restore: bool = False,
) -> str | None:
    """
    Full pipeline: parse -> resolve TFM -> render -> optionally write -> optionally validate.

    When validate_restore=True:
      - Strips NU1202-incompatible packages via strip_incompatible_packages()
      - Parses project.assets.json to identify true direct vs transitive deps
      - Rewrites the .csproj with only direct deps so NuGet resolves transitives
        naturally, giving Semgrep a lockfile with correct direct/transitive labels
      - Runs a final dotnet restore to produce the clean lockfile

    Returns the rendered csproj string (useful for stdout mode).
    """
    packages = parse_packages_config(input_path)

    if not packages:
        print(f"  [WARN] No packages found in {input_path} - skipping.", file=sys.stderr)
        return None

    tfm = resolve_target_framework(packages)

    if output_path is None:
        return build_csproj(packages, tfm)

    if dry_run:
        print(f"  [DRY RUN] Would write {len(packages)} packages -> {output_path}")
        return build_csproj(packages, tfm)

    if validate_restore:
        # Step 1: Write all packages, strip NU1202 incompatibles
        compatible = strip_incompatible_packages(packages, output_path, tfm)
        if not compatible:
            return None

        # Step 2: Parse project.assets.json to split direct vs transitive
        direct, transitive = resolve_direct_packages(compatible, output_path)

        if transitive:
            print(
                f"  [INFO] Direct/transitive split: {len(direct)} direct, "
                f"{len(transitive)} transitive (will be resolved by NuGet automatically)",
                file=sys.stderr,
            )

        # Step 3: Rewrite .csproj with ONLY direct deps
        # NuGet restore will pull in the transitives naturally, and the resulting
        # packages.lock.json will have the correct direct/transitive labels
        final_content = build_csproj(direct if direct else compatible, tfm)
        output_path.write_text(final_content, encoding="utf-8")

        # Step 4: Final restore to produce clean lockfile
        success, _ = _try_restore(output_path)
        if not success:
            print(
                f"  [WARN] Final restore failed after direct/transitive rewrite - "
                f"reverting to full package list.",
                file=sys.stderr,
            )
            # Revert to full compatible list so Semgrep gets something
            fallback_content = build_csproj(compatible, tfm)
            output_path.write_text(fallback_content, encoding="utf-8")
            _try_restore(output_path)

        used = direct if direct else compatible
        print(
            f"  [OK] {input_path} -> {output_path} "
            f"({len(used)} direct / {len(compatible)} total packages, TFM: {tfm})"
        )
        return output_path.read_text(encoding="utf-8")

    else:
        csproj_content = build_csproj(packages, tfm)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(csproj_content, encoding="utf-8")
        print(f"  [OK] {input_path} -> {output_path} ({len(packages)} packages, TFM: {tfm})")
        return csproj_content


# ---------------------------------------------------------------------------
# Directory scan mode
# ---------------------------------------------------------------------------

SYNTHETIC_SUBDIR = "_semgrep_sc"
SYNTHETIC_FILENAME = "project.csproj"


def scan_directory(root_dir: Path, dry_run: bool = False, validate_restore: bool = False) -> int:
    found = list(root_dir.rglob("packages.config"))

    if not found:
        print(f"No packages.config files found under {root_dir}", file=sys.stderr)
        return 0

    print(f"Found {len(found)} packages.config file(s):\n")
    count = 0
    for cfg_path in found:
        output_path = cfg_path.parent / SYNTHETIC_SUBDIR / SYNTHETIC_FILENAME
        try:
            result = convert(
                cfg_path,
                output_path,
                dry_run=dry_run,
                validate_restore=validate_restore,
            )
            if result is not None:
                count += 1
        except ValueError as e:
            print(f"  [ERROR] {e}", file=sys.stderr)

    return count


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert packages.config -> synthetic .csproj for Semgrep Supply Chain",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "input",
        nargs="?",
        metavar="PACKAGES_CONFIG",
        help="Path to a single packages.config file",
    )
    mode.add_argument(
        "--scan-dir",
        metavar="DIR",
        help="Recursively find and convert all packages.config files under DIR",
    )

    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT_CSPROJ",
        help="Output path for the synthetic .csproj (single-file mode only). Defaults to stdout.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without writing any files",
    )
    parser.add_argument(
        "--validate-restore",
        action="store_true",
        help=(
            "After writing each synthetic .csproj: strip NU1202-incompatible packages, "
            "parse project.assets.json to identify true direct deps, rewrite the .csproj "
            "with only direct deps so NuGet resolves transitives naturally, then run a "
            "final restore. Produces a lockfile with correct direct/transitive labels for "
            "Semgrep. Requires dotnet on PATH. Slower but highest-quality output."
        ),
    )

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if args.scan_dir:
        root = Path(args.scan_dir)
        if not root.is_dir():
            print(f"ERROR: --scan-dir '{root}' is not a directory.", file=sys.stderr)
            sys.exit(1)
        count = scan_directory(
            root,
            dry_run=args.dry_run,
            validate_restore=args.validate_restore,
        )
        print(f"\nDone. {count} file(s) converted.")
        sys.exit(0)

    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"ERROR: '{input_path}' not found or is not a file.", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output) if args.output else None

    result = convert(
        input_path,
        output_path,
        dry_run=args.dry_run,
        validate_restore=args.validate_restore,
    )

    if output_path is None and result is not None:
        print(result)


if __name__ == "__main__":
    main()
